sitepost/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from sitepost.models import SitePost

urlpatterns = patterns('', 
    (r'^sitepost/(?P<object_id>\d+)/(?P<slug>[\w-]+)?/?$', 'django.views.generic.list_detail.object_detail', {
        'queryset' : SitePost.live.all(),
    }, 'objects'),
    
    (r'^posts/', 'django.views.generic.simple.direct_to_template', {
        'template' : 'sitepost/post_sites.html', 
    }, 'posts'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
        'show_indexes' : True
    }),
    (r'^', include('sitepost.urls', namespace='sitepost')),
)

sitepost/models.py
import os
from django.db import models
from django.conf import settings
from datetime import datetime, date
from django.utils.safestring import mark_safe
from bbcode.render import RenderBBcode
from sorl.thumbnail.fields import ImageWithThumbnailsField
from PIL import Image
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from sitepost.managers import LiveManager
from sitepost.fields import SlugNullField
import re  
    
class SitePost(models.Model, RenderBBcode):
    
    FORMAT_CHOICES = (
        ('html', 'Raw HTML'),
        ('bbcode', 'BBCode (recommended)'),
    )
    
    STATUS_CHOICES = (
        (0, 'Offline'),
        (3, 'Preview'),
        (5, 'Live'),
    )        

    status = models.IntegerField(choices=STATUS_CHOICES, default=5)
    status.help_text = 'Use this to take items off the site without deleting them'
    title = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)   
    teaser = models.TextField(blank=True, null=True)
    slug = SlugNullField(null=True, blank=True, unique=True, max_length=255)
    user = models.ForeignKey(User, blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True, null=True)
    
    start_date = models.DateField(blank=True, null=True)
    start_date.help_text = 'When the event starts'
    start_time = models.TimeField(blank=True, null=True)
    start_time.help_text = 'All day events can leave this blank'
    end_date = models.DateField(blank=True, null=True)
    end_date.help_text = '1-Day events can leave this'
    end_time = models.TimeField(blank=True, null=True)
    
    format = models.CharField(max_length=6, choices=FORMAT_CHOICES, default='bbcode')
    sites = models.ManyToManyField(Site)
    sites.help_text = 'Choose which site(s) this post will appear on'       
    
    def __unicode__(self):
        return self.title
    
    #soley used for admin to create a many to many list_display field
    def sites_attached(self):
        name = None
        s = self.sites.all()
        for x in s:
            if name:
                name = """%s | %s""" % (name, x.name)
            else:
                name =  """%s """ % (x.name)
        return name        
    
    def images(self):
        return SitePostImage.objects.all().filter(site_post=self)
    
    def images_mapped(self):
        """
        This returns the images as a dictionary indexed by positioning
        """
        try:
            return dict([x for x in enumerate(self.images())])
        except:
            return None        
    
    @models.permalink
    def get_absolute_url(self):
        return ('sitepost:objects', [self.pk, self.slug])
    
    @property
    def get_full_url(self):
        domain = Site.objects.get_current().domain
        path = self.get_absolute_url()
        return 'http://%s%s' % (domain, path)
    
    objects = models.Manager()
    live = LiveManager()
    
class SitePostImage(models.Model):
    """
    This is a quick and easy way for the site editor to link a number of images to a post.
    They then insert them via bb-code syntax in the news post itself
    """
    image = ImageWithThumbnailsField(
        upload_to='uploads/news/',
        thumbnail={'size' : (675, 300), 'options' : ['crop']},
    )
    link = models.CharField(max_length=255, blank=True, null=True)
    order = models.IntegerField(blank=True, null=True)
    site_post = models.ForeignKey(SitePost, blank=True, null=True)
    
    class Meta:
        ordering = ('order',)

sitepost/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseForbidden
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.core import serializers
from django.utils import simplejson as json
from radio.models import Show, PodcastSeries, RadioSkin
from django.conf import settings

PLAYER_TITLE = None
PAGE_TITLE = 'Spine Radio'

if hasattr(settings, 'RADIO_PLAYER_TITLE'):
    PLAYER_TITLE = settings['RADIO_PLAYER_TITLE']
if hasattr(settings, 'RADIO_PAGE_TITLE'):
    PAGE_TITLE = settings['RADIO_PAGE_TITLE']

def showdump(request):
    """ Dumps out the show data as a JSON array for loading into other
    programs (flash maybe? :) """

    return_data = list()
    shows = Show.live.all()[:10]
    for show in shows:
        return_data.append({
            'pk': show.pk,
            'media': show.media.url,
            'image': 'img/shows/active-%s.png' % show.picture,
            'title': show.title,
            'description': show.description,
            'created': show.created_at.strftime('%d/%m/%y %H:%M'),
        })
    return HttpResponse(json.dumps(dict(shows=return_data)))

def player(request):
    skin = RadioSkin.get_active()
    context = {
        'page_title': PAGE_TITLE,
        'player_title': PLAYER_TITLE,
        'skin': skin,
    }
    return render_to_response('radio/container.html', context,
        context_instance=RequestContext(request))

def series(request, slug):
    skin = RadioSkin.get_active()
    context = {
        'page_title': PAGE_TITLE,
        'player_title': PLAYER_TITLE,
        'skin': skin,
        'slug': slug,
    }
    return render_to_response('radio/container.html', context,
        context_instance=RequestContext(request))

def embed(request, object_id):
    show = get_object_or_404(Show, pk=object_id)
    return HttpResponse(show.embed_code)

def download(request, object_id):
    show = get_object_or_404(Show, pk=object_id)
    if show.allow_download:
        return HttpResponseRedirect(show.absolute_media_url)
    else:
        return HttpResponseForbidden()

def playing(request, object_id):
    show = get_object_or_404(Show, pk=object_id)
    return HttpResponseRedirect(show.absolute_media_url)

def play(request, object_id):
    show = get_object_or_404(Show, pk=object_id)
    if show.media:
        return HttpResponse(json.dumps(dict(show=show.media.url)), mimetype='application/json')
    else:
        raise Http404

def get_bare_player(request, object_id):
    show = get_object_or_404(Show, pk=object_id)
    if show.media or show.media_url:
        return HttpResponse(show.flash_player)
    else:
        raise Http404

def podcast_xml(request, slug):
    podcast = get_object_or_404(PodcastSeries, url=slug)
    base_domain = 'http://www.spinetv.net' # HACKALERT! TODO: pull from sites
    return render_to_response('radio/podcast.xml', {'podcast': podcast, 'base_domain': base_domain },
        mimetype='text/xml')

sitepost/templates/sitepost/post_sites.html
{% extends 'master.html' %}
{% load sitepost_media_tags facebook_tags twitter_tags %}

{% block head %}
    {{ block.super }}
    {% render_gmaps_media %}
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL}}js/list_sites.js"></script>
{% endblock %}

{% block post %}
    {% list_posts "1,2,3" %}
{% endblock %}

sitepost/templates/sitepost/sitepost_detail.html
{% extends 'master.html' %}
{% load sitepost_media_tags facebook_tags twitter_tags %}

{% block head %}
    {% render_gmaps_media %}
    {% facebook_like_meta object %}      
{% endblock %}

{% block javascript %}   
    
{% endblock %}

{% block css %}	
	
{% endblock %}        

{% block body %}
    <body>
      {% facebook_except %}
      {% block post %}
	<div class="post">
	    <h3>{{ object.title }}</h3>
	    <h4>Posted {{ object.created_at }} by <span class="username">
		{% block posted_by %}{{ object.user.first_name }}{% endblock %}</span></h4>        
	    {% comment %}<div class="post-teaser">{{ object.actual_teaser|safe }}</div>{% endcomment %}
	    <div class="post-body">{{ object.render_body|safe }}</div>      
	    <div class="post-socialmedia">			                
		{% facebook_like_iframe object %}
		{% twitter object %}             
	    </div>   
	</div>
      {% endblock %}			
    </body>           
{% endblock %}

sitepost/templates/tags/googlemaps_script.html
<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ GMAPS_KEY }}" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}js/googlemaps.js" type="text/javascript"></script>
<link href="{{ MEDIA_URL }}css/google-map-size.css" type="text/css" rel="stylesheet"> 

sitepost/templates/tags/list_posts.html
{% load sitepost_media_tags facebook_tags twitter_tags %}

<ul class="site_post_list">   
    <li id="list_selector">
        {% for site in sites  %}
            <a href="#" id="show_site_{{ forloop.counter }}">Site id: {{ site.id }}</a><br />
        {% endfor %}
    </li>
    <li class="site_list">
        {% for site in sites %}        
            <ul id="site_list_{{ forloop.counter}}">
                Site: {{ site.name }}
                {% for post in site.sitepost_set.all|dictsortreversed:"created_at" %}
                    <li>                    
                        <div class="post">
                            <h3>{{ post.title }}</h3>
                            <h4>Posted {{ post.created_at }} by <span class="username">
                                {% block posted_by %}{{ post.user.first_name }}{% endblock %}</span></h4>        
                            {% comment %}<div class="post-teaser">{{ post.actual_teaser|safe }}</div>{% endcomment %}
                            <div class="post-body">{{ post.render_body|safe }}</div>      
                            <div class="post-socialmedia">         
                                {% facebook_like_iframe post %}
                                {% twitter post %}             
                            </div>   
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
        </ul> 
    </li>   
</ul>

social/templates/tags/facebook_exceptions.html
{% for key, value in fb_errors.items reversed %}
   <span style="color:red;">{{ key }}: {{ value }}</span> <br>
{% endfor %}

social/templates/tags/facebook_like_iframe.html
<div class="facebook_like">
        <iframe src="http://www.facebook.com/plugins/like.php?href={{ fblike_url }}&amp;
        layout=button_count&amp;show_faces=true&amp;width=450&amp;action=like&amp;
        font=lucida+grande&amp;colorscheme=light&amp;height=21" scrolling="no" 
        frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" 
        allowTransparency="true"></iframe>
</div>      

social/templates/tags/facebook_like_meta.html
<meta property="og:title" content="{{ fblike_meta.title }}"/>
<meta property="og:type" content="{{ fblike_meta.type }}"/>
<meta property="og:image" content="{{ fblike_meta.image }}"/>
<meta property="og:url" content="{{ fblike_meta.url }}"/>
<meta property="og:site_name" content="{{ fblike_meta.site_name }}"/>
<meta property="fb:admins" content="{{ fblike_meta.fbadmins }}"/>

social/templates/tags/twitter.html
<div class="twitter">
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
<a href="http://twitter.com/share" class="twitter-share-button"
      data-url="{{ tweet_url }}"
      data-via="{{ tweet_via }}"
      data-text="{{ tweet_title }}"
      data-related="anywhere:The Javascript API"
      data-count="horizontal">Tweet</a>
</div>

templates/master.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml">
    <head>
	<title>django-generic-post</title>
        {% block head %}
	    
	    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>  
	{% endblock %} 
		    
        {% block javascript %}	   
	    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.4.4.js"></script>	    
	{% endblock %}   
		    
        {% block css %}
        {% endblock %}    
    </head>
   

    <body>
     {% block body %}
	   {% block post %}
	   {% endblock %}
       {% endblock %}      
    </body>            
  
</html>